### PR TITLE
Fix data races

### PR DESCRIPTION
**Pull request by slytomcat**

### CODE REVIEW

**Comment by slytomcat** [comment]
This in instead of [previous one](https://github.com/fyne-io/systray/pull/16).

I've resolved all conflicts and removed commit with refresh limiting,

**Comment by Jacalz** [comment]
You might want to keep the PR as a draft (there is a button under the reviews section) until all the unnecessary changes are removed.

**Comment by slytomcat** [comment]
I've reviewed all changes and see nothing more to remove (at least from my point of view).

**Comment by Jacalz** [comment]
You need to remove the module changes and embed stuff. We need to still support the older Go versions.

**Comment by slytomcat** [comment]
Ok. done

**Review by andydotxyz — APPROVED** [review]
Thanks so much for this!

**Pull request merged**
