### PR TITLE
add systray.TrayOpenedCh which is triggered every time user clicks system tray

### PR DESCRIPTION
**Pull request by pymq**
My use case is to refresh some data each time user clicks icon and update submenus

Unfortunately I don't have mac to implement it on darwin 

Probably related to #23

### CODE REVIEW

**Comment by andydotxyz** [comment]
Won't the unix implementation trigger every time a submenu is opened as well? This doesn't sound like what you intended from the PR title.

**Comment by pymq** [comment]
oh, thanks, you are right! fixed that

**Comment by andydotxyz** [comment]
Is there any way (or anyone listening) to get the macOS support added?

**Comment by pymq** [comment]
I found this [example](https://stackoverflow.com/q/59635971) of similar feature, maybe it will help somebody. Without ways to test it I can't implement this, unfortunately

**Comment by davidnewhall** [comment]
🖖 I'd be happy to help test, but my usefulness at adapting Xcode/cocoa is pretty limited. The SO you linked looks promising, but all that "low-level" code is just not something I'm familiar with. That said, I maintain two heavily used apps that import the getlantern variant of this library. The fyne-io version seems like it should drop right in. I'm specifically looking for a way to open the apps' web ui when the menu is double-clicked. This contribution doesn't quite nail that, but it's pretty close, and moving it forward should make my goal easier to get to. If you'd like to stick some code into a branch and link me up, I'll tell you what happens on a Mac, at least. Might even be able to tinker on it. You can also drop my by discord and we can chat. https://golift.io/discord

**Comment by thallgren** [comment]
This PR would make our life easier. It also relates to [this ticket](https://github.com/fyne-io/systray/issues/61) that I just created. Anything I can do to help this getting merged? I can test on both Linux and macOS (Intel or Silicon).

**Pull request merged**
